//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cis237InClass6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string id { get; set; }
        public string year { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string type { get; set; }
        public int horsepower { get; set; }
        public int cylinders { get; set; }
    }
}
